name: Issue workflow
on: issues
jobs:
  describe:
    runs-on: ubuntu-20.04
    name: Describe issue
    steps:
      - name: Output issue title
        run: echo "Issue details - ${{ github.event.issue.title }}"   
      - name: Output issue body
        run: echo "Issue body - ${{ github.event.issue.body }}"
      - name: Output issue action
        run: echo "Issue action - ${{ github.event.action }}"