name: Issue workflow
on: issues
jobs:
  describe:
    runs-on: ubuntu-20.04
    name: Describe issue
    steps:
      name: Output issue description
      run: echo "Issue name - ${{ github.event.issue.labels.name }}"   